<?php
/**
 * CSCreateTripRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ChronoSheetsClient\ChronoSheetsClientLibModel;

use \ArrayAccess;
use \ChronoSheetsClient\ObjectSerializer;

/**
 * CSCreateTripRequest Class Doc Comment
 *
 * @category Class
 * @description Contains fields for creating a Trip
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CSCreateTripRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateTripRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'timesheetId' => 'int',
        'vehicleId' => 'int',
        'pathCoordsStringCsv' => 'string',
        'distanceMeters' => 'double',
        'mobilePlatform' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'timesheetId' => 'int32',
        'vehicleId' => 'int32',
        'pathCoordsStringCsv' => null,
        'distanceMeters' => 'double',
        'mobilePlatform' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'timesheetId' => 'TimesheetId',
        'vehicleId' => 'VehicleId',
        'pathCoordsStringCsv' => 'PathCoordsStringCsv',
        'distanceMeters' => 'DistanceMeters',
        'mobilePlatform' => 'MobilePlatform'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'timesheetId' => 'setTimesheetId',
        'vehicleId' => 'setVehicleId',
        'pathCoordsStringCsv' => 'setPathCoordsStringCsv',
        'distanceMeters' => 'setDistanceMeters',
        'mobilePlatform' => 'setMobilePlatform'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'timesheetId' => 'getTimesheetId',
        'vehicleId' => 'getVehicleId',
        'pathCoordsStringCsv' => 'getPathCoordsStringCsv',
        'distanceMeters' => 'getDistanceMeters',
        'mobilePlatform' => 'getMobilePlatform'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CS_MOBILE_PLATFORM_UNKNOWN = 'Unknown';
    const CS_MOBILE_PLATFORM_I_OS = 'iOS';
    const CS_MOBILE_PLATFORM_ANDROID = 'Android';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMobilePlatformAllowableValues()
    {
        return [
            self::CS_MOBILE_PLATFORM_UNKNOWN,
            self::CS_MOBILE_PLATFORM_I_OS,
            self::CS_MOBILE_PLATFORM_ANDROID,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['timesheetId'] = isset($data['timesheetId']) ? $data['timesheetId'] : null;
        $this->container['vehicleId'] = isset($data['vehicleId']) ? $data['vehicleId'] : null;
        $this->container['pathCoordsStringCsv'] = isset($data['pathCoordsStringCsv']) ? $data['pathCoordsStringCsv'] : null;
        $this->container['distanceMeters'] = isset($data['distanceMeters']) ? $data['distanceMeters'] : null;
        $this->container['mobilePlatform'] = isset($data['mobilePlatform']) ? $data['mobilePlatform'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getMobilePlatformAllowableValues();
        if (!is_null($this->container['mobilePlatform']) && !in_array($this->container['mobilePlatform'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'mobilePlatform', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets timesheetId
     *
     * @return int
     */
    public function getTimesheetId()
    {
        return $this->container['timesheetId'];
    }

    /**
     * Sets timesheetId
     *
     * @param int $timesheetId The associated Timesheet record Id.  The Trip will be linked to the Timesheet with this TimesheetId
     *
     * @return $this
     */
    public function setTimesheetId($timesheetId)
    {
        $this->container['timesheetId'] = $timesheetId;

        return $this;
    }

    /**
     * Gets vehicleId
     *
     * @return int
     */
    public function getVehicleId()
    {
        return $this->container['vehicleId'];
    }

    /**
     * Sets vehicleId
     *
     * @param int $vehicleId The associated Vehicle Id.  The Trip will show that this Vehicle was used
     *
     * @return $this
     */
    public function setVehicleId($vehicleId)
    {
        $this->container['vehicleId'] = $vehicleId;

        return $this;
    }

    /**
     * Gets pathCoordsStringCsv
     *
     * @return string
     */
    public function getPathCoordsStringCsv()
    {
        return $this->container['pathCoordsStringCsv'];
    }

    /**
     * Sets pathCoordsStringCsv
     *
     * @param string $pathCoordsStringCsv A CSV of GPS path co-ordinates.  Format example: -37.8433562,144.7226188;[Lat1],[Long1];........[LatN],[LongN]
     *
     * @return $this
     */
    public function setPathCoordsStringCsv($pathCoordsStringCsv)
    {
        $this->container['pathCoordsStringCsv'] = $pathCoordsStringCsv;

        return $this;
    }

    /**
     * Gets distanceMeters
     *
     * @return double
     */
    public function getDistanceMeters()
    {
        return $this->container['distanceMeters'];
    }

    /**
     * Sets distanceMeters
     *
     * @param double $distanceMeters The total distance of the Trip
     *
     * @return $this
     */
    public function setDistanceMeters($distanceMeters)
    {
        $this->container['distanceMeters'] = $distanceMeters;

        return $this;
    }

    /**
     * Gets mobilePlatform
     *
     * @return string
     */
    public function getMobilePlatform()
    {
        return $this->container['mobilePlatform'];
    }

    /**
     * Sets mobilePlatform
     *
     * @param string $mobilePlatform The Mobile platform that the Trip was recorded on
     *
     * @return $this
     */
    public function setMobilePlatform($mobilePlatform)
    {
        $allowedValues = $this->getMobilePlatformAllowableValues();
        if (!is_null($mobilePlatform) && !in_array($mobilePlatform, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'mobilePlatform', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mobilePlatform'] = $mobilePlatform;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


