<?php
/**
 * CSUsualHoursDay
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ChronoSheetsClient\ChronoSheetsClientLibModel;

use \ArrayAccess;
use \ChronoSheetsClient\ObjectSerializer;

/**
 * CSUsualHoursDay Class Doc Comment
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CSUsualHoursDay implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'UsualHoursDay';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'dayType' => 'string',
        'timeSlots' => '\ChronoSheetsClient\ChronoSheetsClientLibModel\CSTimeSlot[]',
        'deleteUsualHours' => 'int[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'dayType' => null,
        'timeSlots' => null,
        'deleteUsualHours' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'dayType' => 'DayType',
        'timeSlots' => 'TimeSlots',
        'deleteUsualHours' => 'DeleteUsualHours'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'dayType' => 'setDayType',
        'timeSlots' => 'setTimeSlots',
        'deleteUsualHours' => 'setDeleteUsualHours'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'dayType' => 'getDayType',
        'timeSlots' => 'getTimeSlots',
        'deleteUsualHours' => 'getDeleteUsualHours'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const CS_DAY_TYPE_MONDAY = 'Monday';
    const CS_DAY_TYPE_TUESDAY = 'Tuesday';
    const CS_DAY_TYPE_WEDNESDAY = 'Wednesday';
    const CS_DAY_TYPE_THURSDAY = 'Thursday';
    const CS_DAY_TYPE_FRIDAY = 'Friday';
    const CS_DAY_TYPE_SATURDAY = 'Saturday';
    const CS_DAY_TYPE_SUNDAY = 'Sunday';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDayTypeAllowableValues()
    {
        return [
            self::CS_DAY_TYPE_MONDAY,
            self::CS_DAY_TYPE_TUESDAY,
            self::CS_DAY_TYPE_WEDNESDAY,
            self::CS_DAY_TYPE_THURSDAY,
            self::CS_DAY_TYPE_FRIDAY,
            self::CS_DAY_TYPE_SATURDAY,
            self::CS_DAY_TYPE_SUNDAY,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['dayType'] = isset($data['dayType']) ? $data['dayType'] : null;
        $this->container['timeSlots'] = isset($data['timeSlots']) ? $data['timeSlots'] : null;
        $this->container['deleteUsualHours'] = isset($data['deleteUsualHours']) ? $data['deleteUsualHours'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getDayTypeAllowableValues();
        if (!in_array($this->container['dayType'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'dayType', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowedValues = $this->getDayTypeAllowableValues();
        if (!in_array($this->container['dayType'], $allowedValues)) {
            return false;
        }
        return true;
    }


    /**
     * Gets dayType
     *
     * @return string
     */
    public function getDayType()
    {
        return $this->container['dayType'];
    }

    /**
     * Sets dayType
     *
     * @param string $dayType Specify which day this collection of Roster timeslots is for (Monday-Sunday)
     *
     * @return $this
     */
    public function setDayType($dayType)
    {
        $allowedValues = $this->getDayTypeAllowableValues();
        if (!is_null($dayType) && !in_array($dayType, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'dayType', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['dayType'] = $dayType;

        return $this;
    }

    /**
     * Gets timeSlots
     *
     * @return \ChronoSheetsClient\ChronoSheetsClientLibModel\CSTimeSlot[]
     */
    public function getTimeSlots()
    {
        return $this->container['timeSlots'];
    }

    /**
     * Sets timeSlots
     *
     * @param \ChronoSheetsClient\ChronoSheetsClientLibModel\CSTimeSlot[] $timeSlots A collection of TimeSlots within this day
     *
     * @return $this
     */
    public function setTimeSlots($timeSlots)
    {
        $this->container['timeSlots'] = $timeSlots;

        return $this;
    }

    /**
     * Gets deleteUsualHours
     *
     * @return int[]
     */
    public function getDeleteUsualHours()
    {
        return $this->container['deleteUsualHours'];
    }

    /**
     * Sets deleteUsualHours
     *
     * @param int[] $deleteUsualHours Mark here which existing UsualHours are to be deleted
     *
     * @return $this
     */
    public function setDeleteUsualHours($deleteUsualHours)
    {
        $this->container['deleteUsualHours'] = $deleteUsualHours;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


