<?php
/**
 * CSInsertUserRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChronoSheets API
 *
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChronoSheetsClient;

/**
 * CSInsertUserRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description CSInsertUserRequest
/**
 * @package     ChronoSheetsClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CSInsertUserRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CSInsertUserRequest"
     */
    public function testCSInsertUserRequest()
    {
    }

    /**
     * Test attribute "emailAddress"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "isSubscribedToNewsletter"
     */
    public function testPropertyIsSubscribedToNewsletter()
    {
    }

    /**
     * Test attribute "roles"
     */
    public function testPropertyRoles()
    {
    }

    /**
     * Test attribute "alertSettings"
     */
    public function testPropertyAlertSettings()
    {
    }

    /**
     * Test attribute "userName"
     */
    public function testPropertyUserName()
    {
    }

    /**
     * Test attribute "hourlyPayRate"
     */
    public function testPropertyHourlyPayRate()
    {
    }

    /**
     * Test attribute "hourlyOvertimePayRate"
     */
    public function testPropertyHourlyOvertimePayRate()
    {
    }

    /**
     * Test attribute "currentDate"
     */
    public function testPropertyCurrentDate()
    {
    }
}
