<?php
/**
 * CSJobTotalsReportItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChronoSheets API
 *
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChronoSheetsClient;

/**
 * CSJobTotalsReportItemTest Class Doc Comment
 *
 * @category    Class */
// * @description CSJobTotalsReportItem
/**
 * @package     ChronoSheetsClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CSJobTotalsReportItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CSJobTotalsReportItem"
     */
    public function testCSJobTotalsReportItem()
    {
    }

    /**
     * Test attribute "organisationId"
     */
    public function testPropertyOrganisationId()
    {
    }

    /**
     * Test attribute "jobId"
     */
    public function testPropertyJobId()
    {
    }

    /**
     * Test attribute "jobCode"
     */
    public function testPropertyJobCode()
    {
    }

    /**
     * Test attribute "clientId"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "clientName"
     */
    public function testPropertyClientName()
    {
    }

    /**
     * Test attribute "projectId"
     */
    public function testPropertyProjectId()
    {
    }

    /**
     * Test attribute "projectName"
     */
    public function testPropertyProjectName()
    {
    }

    /**
     * Test attribute "spanSeconds"
     */
    public function testPropertySpanSeconds()
    {
    }
}
