<?php
/**
 * CSUpdateMyProfileRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChronoSheetsClient;

/**
 * CSUpdateMyProfileRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CSUpdateMyProfileRequest
 * @package     ChronoSheetsClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CSUpdateMyProfileRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CSUpdateMyProfileRequest"
     */
    public function testCSUpdateMyProfileRequest()
    {
    }

    /**
     * Test attribute "emailAddress"
     */
    public function testPropertyEmailAddress()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "oldPassword"
     */
    public function testPropertyOldPassword()
    {
    }

    /**
     * Test attribute "newPassword"
     */
    public function testPropertyNewPassword()
    {
    }

    /**
     * Test attribute "confirmNewPassword"
     */
    public function testPropertyConfirmNewPassword()
    {
    }

    /**
     * Test attribute "isSubscribedToNewsletter"
     */
    public function testPropertyIsSubscribedToNewsletter()
    {
    }

    /**
     * Test attribute "wantsToChangePassword"
     */
    public function testPropertyWantsToChangePassword()
    {
    }
}
