<?php
/**
 * InsertTaskRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ChronoSheetsClient;

use PHPUnit\Framework\TestCase;

/**
 * InsertTaskRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Fields for inserting a new Task
 * @package     ChronoSheetsClient
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InsertTaskRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InsertTaskRequest"
     */
    public function testInsertTaskRequest()
    {
    }

    /**
     * Test attribute "taskName"
     */
    public function testPropertyTaskName()
    {
    }

    /**
     * Test attribute "tripEnabled"
     */
    public function testPropertyTripEnabled()
    {
    }
}
