<?php
/**
 * JobCodesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChronoSheets API
 *
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ChronoSheetsClient;

use \ChronoSheetsClient\Configuration;
use \ChronoSheetsClient\ApiException;
use \ChronoSheetsClient\ObjectSerializer;

/**
 * JobCodesApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobCodesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for jobCodesCreateJobCode
     *
     * Create a job code.
     *
     */
    public function testJobCodesCreateJobCode()
    {
    }

    /**
     * Test case for jobCodesDeleteJobCode
     *
     * Delete a job code.
     *
     */
    public function testJobCodesDeleteJobCode()
    {
    }

    /**
     * Test case for jobCodesGetJobCodeById
     *
     * Get a particular job code by job code id.
     *
     */
    public function testJobCodesGetJobCodeById()
    {
    }

    /**
     * Test case for jobCodesGetJobCodes
     *
     * Get job codes for your organisation.
     *
     */
    public function testJobCodesGetJobCodes()
    {
    }

    /**
     * Test case for jobCodesUpdateJobCode
     *
     * Update a job code.
     *
     */
    public function testJobCodesUpdateJobCode()
    {
    }
}
