<?php
/**
 * TimesheetsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace ChronoSheetsClient;

use \ChronoSheetsClient\Configuration;
use \ChronoSheetsClient\ApiException;
use \ChronoSheetsClient\ObjectSerializer;

/**
 * TimesheetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChronoSheetsClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TimesheetsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for timesheetsCreateSingleTimesheet
     *
     * Inserts a single timesheet record.    Requires the 'SubmitTimesheets' permission..
     *
     */
    public function testTimesheetsCreateSingleTimesheet()
    {
    }

    /**
     * Test case for timesheetsDeleteTimesheet
     *
     * Delete a timesheet.    Requires the 'SubmitTimesheets' permission..
     *
     */
    public function testTimesheetsDeleteTimesheet()
    {
    }

    /**
     * Test case for timesheetsGetTimesheets
     *
     * Get timesheets between start and end dates.  Note: the date range cannot exceed 24 hours.  This method is generally used to get timesheets for a particular day.    Requires the 'SubmitTimesheets' permission..
     *
     */
    public function testTimesheetsGetTimesheets()
    {
    }

    /**
     * Test case for timesheetsUpdateTimesheets
     *
     * Batch update timesheets.    Requires the 'SubmitTimesheets' permission..
     *
     */
    public function testTimesheetsUpdateTimesheets()
    {
    }
}
